# Generated by Django 4.2.1 on 2023-05-12 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=128)),
                ('lastName', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PublishingHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namePublish', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('site', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=128)),
                ('yearPublish', models.DateTimeField()),
                ('countPage', models.IntegerField()),
                ('hardcover', models.CharField(max_length=128)),
                ('abstract', models.CharField(max_length=128)),
                ('status', models.BooleanField()),
                ('authorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='books_app.authors')),
                ('publishId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='books_app.publishinghouse')),
            ],
        ),
    ]
